version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        columns:
          - name: "(orders_id||'_'||pdt_id)"
            description: primary key of sales tables
            tests:
              - unique
              - not_null
          - name: date_date,
            description: date of purchase
          - name: orders_id,
            description: id of the order
          - name: pdt_id AS products_id,
            description: id of the product
          - name: revenue,
            description: the revenue from the sales
          - name: quantity
            description: number of the purchase
      - name: product
        identifier: raw_gz_product
        description: products that Greenweez have
        columns:
          - name: products_id
            description: PK of the product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the price that customer pays
      - name: ship
        identifier: raw_gz_ship
        description: shipping information of Greenweez sales
        columns:
          - name: orders_id
            description: PK of the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the fee of the shipping for every order
          - name: logcost
            description: logistic cost of the order
          - name: ship_cost
            description: shipping cost of the order
      - name: adwords
        identifier: raw_gz_adwords
        description: advertisemant words
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: click
      - name: bing
        identifier: raw_gz_bing
        description: Bingo information
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo information
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaign information
        columns:
          - name: date_date
          - name: paid_sources
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

models:
  #Intermediate#

  - name: int_orders_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: PK of the table
        tests:
          - unique
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: revenue
        description: sum of revenue per order
        tests:
          - not_null
      - name: quantity
        description: sum of quantity per order
        tests:
          - not_null
      - name: purchase_cost
        description: quantity*purchase_price
        tests:
          - not_null:
              config:
                severity: warn
      - name: margin
        description: revenue-purchase_cost
        tests:
          - not_null
  - name: int_orders_operational
    description: operational margin calculation per order
    columns:
      - name: orders_id
        description: PK
        tests:
          - unique
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: margin
        description: revenue-purchase_cost
        tests:
          - not_null
      - name: quantity
        description: sum of quantity per order
        tests:
          - not_null
      - name: revenue
        description: sum of revenue per order
        tests:
          - not_null
      - name: purchase_cost
        description: quantity*purchase_price
        tests:
          - not_null
      - name: shipping_fee
        description: the price the customer pays for shipping
        tests:
          - not_null
      - name: ship_cost
        description: shipping cost paid by the company to the carrier
        tests:
          - not_null
      - name: logcost
        description: the cost of the preparing the parcel in the distribution centre or warehouse
        tests:
          - not_null:
              config:
                severity: warn

      - name: operational_margin
        description: margin+shipping_fee-(log_cost+ship_cost)
        tests:
          - not_null
  - name: int_sales_margin
    description: margin calculation per order line/product sales
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null
      - name: products_id
        description: products key
        tests:
          - not_null:
              config:
                severity: warn
      - name: margin
        description: revenue-purchase_cost
        tests:
          - not_null:
              config:
                severity: warn
      - name: purchase_cost
        description: quantity*purchase_price
        tests:
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: revenue
        description: sum of the revenue per order
        tests:
          - not_null
      - name: quantity
        description: sum of the quantity per order
        tests:
          - not_null
      - name: ordpdt
        description: PK
        tests:
          - not_null
          - unique
  - name: int_campaigns
    description: campaign all data in one model
    columns:
      - name: date_date
        tests:
          - not_null
      - name: paid_source
        tests:
          - not_null
      - name: campaign_key
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null
      - name: ads_cost
        tests:
          - not_null
      - name: impression
        tests:
          - not_null
      - name: click
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(campaign_key || '-' || date_date)"
  - name: in_campaigns_day
    description: aggregated campaigns data by date
    columns:
      - name: date_date
        description: date of the campaigns
        tests:
          - not_null
      - name: ads_cost
        description: cost of the ads
        tests:
          - not_null
      - name: impression
        description: the impression of the
        tests:
          - not_null
      - name: click
        description: amount of the clicks per day for campaigns
        tests:
          - not_null

  - name: finance_campaigns_day
    description: global kpi
    columns:
      - name: date_date
        description: campaign day
        tests:
          - not_null
      - name: ads_margin
        description: operational margin - ads_cost
        tests:
          - not_null:
              config:
                severity: warn
      - name: average_basket
        description: avg basket cost for each day
        tests:
          - not_null
      - name: operational_margin
        description: margin + shipping_fee - (logcost + ship_cost)
        tests:
          - not_null
      - name: ads_cost
        description: advertisement costs
        tests:
          - not_null:
              config:
                severity: warn
      - name: ads_impression
        description: impression of the adds
        tests:
          - not_null:
              config:
                severity: warn
      - name: ads_clicks
        description: clicks of campaigns in a day
        tests:
          - not_null:
              config:
                severity: warn
      - name: quantity
        description: quantity
        tests:
          - not_null
      - name: revenue
        description: revenue
        tests:
          - not_null
      - name: purchase_cost
        description: quantity * purchase_price
        tests:
          - not_null
      - name: margin
        description: revenue - purchase_cost
        tests:
          - not_null:
              config:
                severity: warn
      - name: shipping_fee
        description: shipping fee that costumers pay
        tests:
          - not_null
      - name: logcost
        description: logistic costs
        tests:
          - not_null
      - name: ship_cost
        description: shipping costs
        tests:
          - not_null